development:
  adapter: postgresql
  encoding: unicode
  database: monash_cms_development
  pool: 5
  username: devuser
  password: devuser
  host: localhost

test:
  adapter: postgresql
  encoding: unicode
  database: monash_cms_test
  pool: 5
  username: devuser
  password: devuser
  host: localhost